// NEXURA Reports — port of buildCaseReportMarkdown / report endpoints.
// Adapted to the local schema (remotefix_* prefixed tables, case_id text PK).

import { getDb } from "./db.js";
import { recordCaseAudit } from "./opportunities.js";

const toHex = (buffer) =>
  Array.from(new Uint8Array(buffer))
    .map((b) => b.toString(16).padStart(2, "0"))
    .join("");

const makeId = (prefix) => {
  const bytes = new Uint8Array(8);
  crypto.getRandomValues(bytes);
  return `${prefix}_${toHex(bytes.buffer)}`;
};

const moneyRange = (minCents, maxCents) =>
  `${Math.round(Number(minCents || 0) / 100)} $ - ${Math.round(Number(maxCents || 0) / 100)} $ CAD`;

const formatList = (value, fallback) => {
  if (!Array.isArray(value) || value.length === 0) return `- ${fallback}`;
  return value.map((x) => `- ${x}`).join("\n");
};

export const buildCaseReportMarkdown = async (env, caseId) => {
  const sql = getDb(env);
  const [cases, triageRows, reportRows, commands, audits] = await Promise.all([
    sql`select * from cases where case_id = ${caseId} limit 1`,
    sql`select * from remotefix_triage_results where case_id = ${caseId} order by created_at desc limit 1`,
    sql`select * from remotefix_diagnostic_reports where case_id = ${caseId} order by created_at desc limit 1`,
    sql`select action, status, created_at from remotefix_agent_commands where case_id = ${caseId} order by created_at desc`,
    sql`select actor, event, created_at from remotefix_audit_logs where case_id = ${caseId} order by created_at asc`
  ]);

  if (!cases.length) throw new Error("Case not found");
  const k = cases[0];
  const t = triageRows[0];
  const r = reportRows[0];

  return `# NEXURA RemoteLab Report

## Case
- Case ID: ${caseId}
- Status: ${k.status}
- Client: ${k.name || "Unknown"}
- Email: ${k.email || "Unknown"}
- Device type: ${k.support || "n/a"}
- Symptom: ${k.symptom || "n/a"}
- Urgency: ${k.urgency || "n/a"}

## Triage
- Service: ${t?.service || "Not available"}
- Mode: ${t?.final_decision || "Not available"}
- Risk: ${t?.risk_label || "Unknown"} (${t?.risk_score ?? "n/a"}/100)
- Estimated value: ${moneyRange(t?.price_min_cents, t?.price_max_cents)}
- Reason: ${t?.reason || "Not available"}
- Next action: ${t?.next_action || "Not available"}

## Do Not Do
${formatList(t?.blocked_actions, "Do not perform destructive actions.")}

## Diagnostic Findings
- Severity: ${r?.severity || "No diagnostic report yet"}
- Summary: ${r?.summary || "No diagnostic report yet"}

## Safe Actions Offered
${formatList(r?.safe_actions_to_offer, "None")}

## Blocked Actions
${formatList(r?.blocked_actions, "Destructive actions remain blocked by policy")}

## Commands
${commands.length ? commands.map((cmd) => `- ${cmd.action}: ${cmd.status}`).join("\n") : "- No commands issued"}

## Audit Timeline
${audits.length ? audits.map((log) => `- ${new Date(log.created_at).toISOString()} — ${log.actor}: ${log.event}`).join("\n") : "- No audit events recorded"}

---
Generated by NEXURA RemoteLab.
`;
};

export const persistGeneratedReport = async (env, caseId) => {
  const markdown = await buildCaseReportMarkdown(env, caseId);
  const reportId = makeId("genreport");
  const sql = getDb(env);

  await sql`insert into generated_reports (id, case_id, report_type, title, body_markdown, metadata)
        values (${reportId}, ${caseId}, 'remotelab_diagnostic', 'NEXURA RemoteLab Report', ${markdown}, ${JSON.stringify({ generatedBy: "api" })}::jsonb)`;

  await recordCaseAudit(env, caseId, "system", "report_generated", { reportId });
  return { reportId, markdown };
};

export const getGeneratedReport = async (env, reportId) => {
  const sql = getDb(env);
  const rows = await sql`select * from generated_reports where id = ${reportId} limit 1`;
  return rows[0] || null;
};
