#!/usr/bin/env bash
# block-build-output.sh
# PreToolUse hook — blocks any write/edit/delete targeting the build output dir.
# That directory is ALWAYS regenerated by `npm run build`. Manual edits are
# silently overwritten on the next build.

set -euo pipefail

INPUT=$(cat)

TOOL_NAME=$(echo "$INPUT" | python3 -c "import sys,json; d=json.load(sys.stdin); print(d.get('tool_name',''))" 2>/dev/null || true)

# Blocked dir stored in a variable — script source never contains the literal path.
BLOCKED_DIR="release-cloudflare"

deny() {
  printf '{"hookSpecificOutput":{"hookEventName":"PreToolUse","permissionDecision":"deny","permissionDecisionReason":"BLOCKED: %s/ is auto-generated build output. Edit source files at the repo root, then run npm run build to regenerate."}}\n' "$BLOCKED_DIR"
  exit 2
}

# File-write tools: inspect only file path fields, not content.
if echo "$TOOL_NAME" | grep -qE "^(create_file|replace_string_in_file|multi_replace_string_in_file)$"; then
  FILE_PATHS=$(echo "$INPUT" | python3 -c "
import sys, json
d = json.load(sys.stdin)
ti = d.get('tool_input', {})
if isinstance(ti, dict):
    paths = [ti.get('filePath', ''), ti.get('file_path', ''), ti.get('path', '')]
    for replacement in ti.get('replacements', []):
        paths.append(replacement.get('filePath', ''))
    print('\\n'.join(p for p in paths if p))
" 2>/dev/null || true)
  if echo "$FILE_PATHS" | grep -qF "${BLOCKED_DIR}/"; then
    deny
  fi
fi

# --- Terminal tool: check only the command for writes into the blocked dir ---
if [ "$TOOL_NAME" = "run_in_terminal" ]; then
  COMMAND=$(echo "$INPUT" | python3 -c "import sys,json; d=json.load(sys.stdin); print(d.get('tool_input',{}).get('command',''))" 2>/dev/null || true)
  if echo "$COMMAND" | grep -qF "${BLOCKED_DIR}/"; then
    deny
  fi
fi

exit 0
