#!/usr/bin/env bash
# css-source-guard.sh
# PreToolUse hook — warns (and blocks) any write/edit targeting
# assets/css/site.css, which is now a generated artifact.
# The authoritative source lives in assets/css/src/*.css and the build
# script (scripts/build-css.mjs) concatenates them in lexicographic order.

set -euo pipefail

INPUT=$(cat)

TOOL_NAME=$(echo "$INPUT" | python3 -c "import sys,json; d=json.load(sys.stdin); print(d.get('tool_name',''))" 2>/dev/null || true)

GENERATED_FILE="assets/css/site.css"
SOURCE_DIR="assets/css/src"

deny() {
  printf '{"hookSpecificOutput":{"hookEventName":"PreToolUse","permissionDecision":"deny","permissionDecisionReason":"BLOCKED: %s is generated by scripts/build-css.mjs. Edit a partial in %s/ instead, then run npm run build."}}\n' "$GENERATED_FILE" "$SOURCE_DIR"
  exit 2
}

if echo "$TOOL_NAME" | grep -qE "^(create_file|replace_string_in_file|multi_replace_string_in_file)$"; then
  FILE_PATHS=$(echo "$INPUT" | python3 -c "
import sys, json
d = json.load(sys.stdin)
ti = d.get('tool_input', {})
paths = []
if isinstance(ti, dict):
    paths = [ti.get('filePath', ''), ti.get('file_path', ''), ti.get('path', '')]
    for replacement in ti.get('replacements', []) or []:
        paths.append(replacement.get('filePath', ''))
print('\\n'.join(p for p in paths if p))
" 2>/dev/null || true)
  if echo "$FILE_PATHS" | grep -qE "(^|/)${GENERATED_FILE}\$"; then
    deny
  fi
fi

exit 0
