#!/usr/bin/env bash
# session-briefing.sh
# SessionStart hook — injects a project-context reminder at the start of every
# agent session so critical rules are always in working memory.

set -euo pipefail

cat <<'EOF'
{
  "hookSpecificOutput": {
    "hookEventName": "SessionStart",
    "additionalContext": "NEXURADATA PROJECT BRIEFING\n\nStack: Cloudflare Pages + Pages Functions · Neon Postgres · Stripe · Resend\n\nCRITICAL RULES:\n1. NEVER edit release-cloudflare/ — it is regenerated by `npm run build`. Edit source files at root.\n2. BILINGUAL: every FR page at root has an EN mirror under en/ with the same filename. Update both.\n3. SECRETS (RESEND_API_KEY, STRIPE_SECRET_KEY, STRIPE_WEBHOOK_SECRET, ACCESS_CODE_SECRET, DATABASE_URL) must never appear in code, logs, or output.\n4. Functions use ESM only — export const onRequest / onRequestPost. No CommonJS.\n5. Operator routes (/api/ops/*, /operations/*) are protected by Cloudflare Access — never add an auth bypass.\n6. Reuse functions/_lib/ helpers — do not duplicate DB, email, or rate-limit logic.\n7. wrangler.jsonc is the single source of truth for env vars and compat date.\n\nBuild: npm run build · Dev: npm run cf:dev · Test: npm test\n\nSee README.md for full architecture and copilot-instructions.md for coding rules."
  }
}
EOF

exit 0
